server:
  port: 8009

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8011/
          predicates:
            - Path=/api/user/**
        - id: forum
          uri: http://localhost:8010/
          predicates:
            - Path=/api/forum/**