spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/spring_db
    user: postgres
    password: igromir.04
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: igromir.04
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8010
